version: '3'

services:
  react_native_app:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - NODE_ENV=development
        - NODE_OPTIONS=--openssl-legacy-provider
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./frontend:/opt/react_native_app/app:delegated
      - ./frontend/package.json:/opt/react_native_app/package.json
      - ./frontend/package-lock.json:/opt/react_native_app/package-lock.json
    healthcheck:
      disable: true

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    links:
      - mysql_db:mysql_db
    depends_on:
      - mysql_db
    volumes:
      - ./backend/build/libs/:/backend/
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/cherishdata?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: always
    stdin_open: true
    tty: true

  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
       - ./mysql/db:/var/lib/mysql
       - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT=%
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234